### ISSUE TITLE
About the result of running sh ./fast_train_test.sh configs/miniImagenet/MEL_N5K1_R12_katz.yaml 0

### ISSUE THREAD

**Issue by allenhaozhu** [LouieYang/MCL#2]
I have no idea why I got a pretty bad result with this command.
test accuracy: 0.3950386666666667 h: 0.0019098219201740024
aver_accuracy: 0.3950386666666667 h: 0.0019098219201740024

would you mind checking the result? Thank you for your help.

**Comment by LouieYang** [comment]
You should place the [pretrained-model](https://drive.google.com/file/d/1Y6yupnGWnXdfPSmh8iH2KJPj06uy9LMH/view?usp=sharing) in that checkpoint first for ResNet-12 before meta-train. 

We will update the README asap.

**Comment by LouieYang** [comment]
README updated. Closed
