### ISSUE TITLE
about train in meta-iNat and tiered meta-iNat dataset

### ISSUE THREAD

**Issue by tf1997** [LouieYang/MCL#6]
This is a excellent work, and I am building my work on it.  I have downloaded the data set. However, during the training, the program prompts "no such file or directory:'/data/mcl/meta_inant/val". I noticed  meta-iNat and tiered meta-iNat dataset have no val set, so I would like to ask the author how to train on the dataset. Thank you!

**Comment by LouieYang** [comment]
Just ignore the train-validation for meta-iNat and tiered-meta-iNat. 

You can directly `ln -s` the `test` to `val` to start the code running and evaluate on the last training epoch.

**Comment by tf1997** [comment]
Thank you for your reply!
