### ISSUE TITLE
Question about the pre-training weight of the tieredimagenet dataset

### ISSUE THREAD

**Issue by WuJi1** [LouieYang/MCL#7]
Dear author, thanks for sharing the codes.

In your google drive shared folder, I find that you only provide the weight of **tieredimagenet-e0_DeepEMD_downloaded.pth** in **ResNet-12/pretrainer**. I would like to ask you whether the weight is the pre-training weight you trained on the **tiered-imagenet_DeepEMD** dataset according to the settings in **MCL/configs/tieredimagenet/pretrainer/FRN_pre.yaml** and whether this weight correspond to the experimental results of resnet-12 on tieredimagenet in your paper.

**Comment by LouieYang** [comment]
Hi, that is the pre-trained weight in the paper.

We directly use the weights downloaded from DeepEMD repo for tiered-imagenet. According to them, pre-training for tieredimagenet takes much effort. 

We did try some pre-training schemes like in **MCL/configs/tieredimagenet/pretrainer/FRN_pre.yaml** but failed to bypass their provided ones. To compare, we use downloaded weights for all tieredimagenet/ResNet settings.

**Comment by WuJi1** [comment]
Thank you very much for your reply. I also tried the setting by this yaml file, but can not get satisfactory pre-training weight on tieredimagenet dataset.
