### ISSUE TITLE
Evaluate the meta-trained model get a bad result

### ISSUE THREAD

**Issue by DiaosWang** [LouieYang/MCL#9]
I try to run this command: 
'python experiments/run_evaluator.py   --cfg ./snapshots/ResNet-12/MEL_katz/VanillaFCN/miniImagenet_MEL_N5K5_R12_kat
z_83.986/MEL_N5K5_R12_katz.yaml   -c ./snapshots/ResNet-12/MEL_katz/VanillaFCN/miniImagenet_MEL_N5K5_R12_katz_83.986/ebest_5way_5shot.pth   --device 0'

and get a bad result :
![image](https://github.com/LouieYang/MCL/assets/47164366/bb32952d-1409-42f1-b820-67d03b171201)

I downloaded the snapshots you provided and I haven't made any changes to the code. The dataset link you provided does not include miniImagenet, so I downloaded the dataset miniImagenet from a different path, but I can ensure its integrity and correctness. Is there a problem with my operation？

**Comment by DiaosWang** [comment]
Looking forward to your reply
thank you !

**Comment by LouieYang** [comment]
Hi. The miniimage dataset is from DeepEMD (or maybe FRN, its been years I am not 100% sure) and you can download it from their webpage. One thing I am sure for miniimagenet is that the image is in their original sizes without pre-cropping to 84x84.

**Comment by DiaosWang** [comment]
thank you for you reply!!!
